<?php

namespace Modules\Entertainment\database\seeders;

use Illuminate\Database\Seeder;

class LikesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        // Clear existing records

        \DB::table('likes')->delete();

        \DB::table('likes')->insert(array (
            0 =>
            array (
                'id' => 1,
                'entertainment_id' => 1,
                'user_id' => 6,
                'is_like' => 1,
                'profile_id' => 6,
                'type'=>'tvshow',
                'created_by' => 6,
                'updated_by' => 6,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:23:07',
                'updated_at' => '2024-09-25 15:23:07',
                'deleted_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'entertainment_id' => 5,
                'user_id' => 6,
                'is_like' => 1,
                'profile_id' => 6,
                'type'=>'tvshow',
                'created_by' => 6,
                'updated_by' => 6,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:24:20',
                'updated_at' => '2024-09-25 15:24:20',
                'deleted_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'entertainment_id' => 10,
                'user_id' => 4,
                'is_like' => 1,
                'profile_id' => 4,
                'type'=>'tvshow',
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:24:27',
                'updated_at' => '2024-09-25 15:24:27',
                'deleted_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'entertainment_id' => 14,
                'user_id' => 4,
                'is_like' => 1,
                'profile_id' => 4,
                'type'=>'tvshow',
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:24:45',
                'updated_at' => '2024-09-25 15:24:45',
                'deleted_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'entertainment_id' => 94,
                'user_id' => 4,
                'is_like' => 1,
                'profile_id' => 4,
                'type'=>'movie',
                'created_by' => 4,
                'updated_by' => 4,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:26:42',
                'updated_at' => '2024-09-25 15:26:42',
                'deleted_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'entertainment_id' => 45,
                'user_id' => 10,
                'is_like' => 1,
                'profile_id' => 10,
                'type'=>'movie',
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:27:07',
                'updated_at' => '2024-09-25 15:27:07',
                'deleted_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'entertainment_id' => 90,
                'user_id' => 12,
                'is_like' => 1,
                'profile_id' => 12,
                'type'=>'movie',
                'created_by' => 4,
                'updated_by' => 4,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:27:19',
                'updated_at' => '2024-09-25 15:27:19',
                'deleted_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'entertainment_id' => 95,
                'user_id' => 12,
                'is_like' => 1,
                'profile_id' => 12,
                'type'=>'movie',
                'created_by' => 6,
                'updated_by' => 6,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:27:31',
                'updated_at' => '2024-09-25 15:27:31',
                'deleted_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'entertainment_id' => 95,
                'user_id' => 7,
                'is_like' => 1,
                'profile_id' => 7,
                'type'=>'movie',
                'created_by' => 7,
                'updated_by' => 7,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:29:34',
                'updated_at' => '2024-09-25 15:29:34',
                'deleted_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'entertainment_id' => 102,
                'user_id' => 7,
                'is_like' => 1,
                'profile_id' => 7,
                'type'=>'movie',
                'created_by' => 7,
                'updated_by' => 7,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:30:12',
                'updated_at' => '2024-09-25 15:30:12',
                'deleted_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'entertainment_id' => 101,
                'user_id' => 7,
                'is_like' => 1,
                'profile_id' => 7,
                'type'=>'movie',
                'created_by' => 7,
                'updated_by' => 7,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:30:24',
                'updated_at' => '2024-09-25 15:30:24',
                'deleted_at' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'entertainment_id' => 99,
                'user_id' => 7,
                'is_like' => 1,
                'profile_id' => 7,
                'type'=>'video',
                'created_by' => 7,
                'updated_by' => 7,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:30:29',
                'updated_at' => '2024-09-25 15:30:29',
                'deleted_at' => NULL,
            ),
            12 =>
            array (
                'id' => 13,
                'entertainment_id' => 14,
                'user_id' => 7,
                'is_like' => 1,
                'profile_id' => 7,
                'type'=>'video',
                'created_by' => 7,
                'updated_by' => 7,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:30:46',
                'updated_at' => '2024-09-25 15:30:46',
                'deleted_at' => NULL,
            ),
            13 =>
            array (
                'id' => 14,
                'entertainment_id' => 10,
                'user_id' => 8,
                'is_like' => 1,
                'profile_id' => 8,
                'type'=>'video',
                'created_by' => 7,
                'updated_by' => 7,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:30:53',
                'updated_at' => '2024-09-25 15:30:53',
                'deleted_at' => NULL,
            ),
            14 =>
            array (
                'id' => 15,
                'entertainment_id' => 5,
                'user_id' => 9,
                'is_like' => 1,
                'profile_id' => 9,
                'type'=>'video',
                'created_by' => 7,
                'updated_by' => 7,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:31:02',
                'updated_at' => '2024-09-25 15:31:02',
                'deleted_at' => NULL,
            ),
            15 =>
            array (
                'id' => 16,
                'entertainment_id' => 1,
                'user_id' => 14,
                'is_like' => 1,
                'profile_id' => 14,
                'type'=>'tvshow',
                'created_by' => 7,
                'updated_by' => 7,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:31:10',
                'updated_at' => '2024-09-25 15:31:10',
                'deleted_at' => NULL,
            ),
            16 =>
            array (
                'id' => 17,
                'entertainment_id' => 1,
                'user_id' => 5,
                'is_like' => 1,
                'profile_id' => 5,
                'type'=>'tvshow',
                'created_by' => 5,
                'updated_by' => 5,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:32:25',
                'updated_at' => '2024-09-25 15:32:25',
                'deleted_at' => NULL,
            ),
            17 =>
            array (
                'id' => 18,
                'entertainment_id' => 5,
                'user_id' => 5,
                'is_like' => 1,
                'profile_id' => 5,
                'type'=>'tvshow',
                'created_by' => 5,
                'updated_by' => 5,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:32:38',
                'updated_at' => '2024-09-25 15:32:38',
                'deleted_at' => NULL,
            ),
            18 =>
            array (
                'id' => 19,
                'entertainment_id' => 89,
                'user_id' => 5,
                'is_like' => 1,
                'profile_id' => 5,
                'type'=>'movie',
                'created_by' => 5,
                'updated_by' => 5,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:32:43',
                'updated_at' => '2024-09-25 15:32:43',
                'deleted_at' => NULL,
            ),
            19 =>
            array (
                'id' => 20,
                'entertainment_id' => 101,
                'user_id' => 5,
                'is_like' => 1,
                'profile_id' => 5,
                'type'=>'move',
                'created_by' => 5,
                'updated_by' => 5,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:32:49',
                'updated_at' => '2024-09-25 15:32:49',
                'deleted_at' => NULL,
            ),
            20 =>
            array (
                'id' => 21,
                'entertainment_id' => 87,
                'user_id' => 5,
                'is_like' => 1,
                'profile_id' => 5,
                'type'=>'movie',
                'created_by' => 5,
                'updated_by' => 5,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:32:53',
                'updated_at' => '2024-09-25 15:32:53',
                'deleted_at' => NULL,
            ),
            21 =>
            array (
                'id' => 22,
                'entertainment_id' => 102,
                'user_id' => 5,
                'is_like' => 1,
                'profile_id' => 5,
                'type'=>'movie',
                'created_by' => 5,
                'updated_by' => 5,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:32:57',
                'updated_at' => '2024-09-25 15:32:57',
                'deleted_at' => NULL,
            ),
            22 =>
            array (
                'id' => 23,
                'entertainment_id' => 97,
                'user_id' => 5,
                'is_like' => 1,
                'profile_id' => 5,
                'type'=>'movie',
                'created_by' => 5,
                'updated_by' => 5,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:33:06',
                'updated_at' => '2024-09-25 15:33:06',
                'deleted_at' => NULL,
            ),
            23 =>
            array (
                'id' => 24,
                'entertainment_id' => 98,
                'user_id' => 5,
                'is_like' => 1,
                'profile_id' => 5,
                'type'=>'movie',
                'created_by' => 5,
                'updated_by' => 5,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:33:13',
                'updated_at' => '2024-09-25 15:33:13',
                'deleted_at' => NULL,
            ),
            24 =>
            array (
                'id' => 25,
                'entertainment_id' => 103,
                'user_id' => 5,
                'is_like' => 1,
                'profile_id' => 5,
                'type'=>'movie',
                'created_by' => 5,
                'updated_by' => 5,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:33:26',
                'updated_at' => '2024-09-25 15:33:26',
                'deleted_at' => NULL,
            ),

            25 =>
            array (
                'id' => 26,
                'entertainment_id' => 100,
                'user_id' => 3,
                'is_like' => 1,
                'profile_id' => 3,
                'type'=>'movie',
                'created_by' => 5,
                'updated_by' => 5,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:33:26',
                'updated_at' => '2024-09-25 15:33:26',
                'deleted_at' => NULL,
            ),

            26 =>
            array (
                'id' => 27,
                'entertainment_id' => 25,
                'user_id' => 3,
                'is_like' => 1,
                'profile_id' => 3,
                'type'=>'movie',
                'created_by' => 5,
                'updated_by' => 5,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:33:26',
                'updated_at' => '2024-09-25 15:33:26',
                'deleted_at' => NULL,
            ),

            27 =>
            array (
                'id' => 28,
                'entertainment_id' => 16,
                'user_id' => 3,
                'is_like' => 1,
                'profile_id' => 3,
                'type'=>'movie',
                'created_by' => 5,
                'updated_by' => 5,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:33:26',
                'updated_at' => '2024-09-25 15:33:26',
                'deleted_at' => NULL,
            ),

            27 =>
            array (
                'id' => 28,
                'entertainment_id' => 16,
                'user_id' => 3,
                'is_like' => 1,
                'profile_id' => 3,
                'type'=>'movie',
                'created_by' => 5,
                'updated_by' => 5,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 15:33:26',
                'updated_at' => '2024-09-25 15:33:26',
                'deleted_at' => NULL,
            ),
        ));


    }
}
