<?php

namespace Modules\Entertainment\database\seeders;

use Illuminate\Database\Seeder;

class ContinueWatchTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('continue_watch')->delete();

        \DB::table('continue_watch')->insert(array (
            0 =>
            array (
                'id' => 1,
                'entertainment_id' => 28,
                'user_id' => 3,
                'profile_id' => 3,
                'entertainment_type' => 'movie',
                'watched_time' => '00:03:00',
                'total_watched_time' => '00:03:00',
                'episode_id' => NULL,
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => NULL,
                'created_at' => '2024-09-26 11:12:14',
                'updated_at' => '2024-09-26 11:12:14',
                'deleted_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'entertainment_id' => 99,
                'user_id' => 3,
                'profile_id' => 3,
                'entertainment_type' => 'movie',
                'watched_time' => '00:06:00',
                'total_watched_time' => '00:06:00',
                'episode_id' => NULL,
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => NULL,
                'created_at' => '2024-09-26 11:13:01',
                'updated_at' => '2024-09-26 11:13:01',
                'deleted_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'entertainment_id' => 87,
                'user_id' => 3,
                'profile_id' => 3,
                'entertainment_type' => 'movie',
                'watched_time' => '00:02:00',
                'total_watched_time' => '00:02:00',
                'episode_id' => NULL,
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => NULL,
                'created_at' => '2024-09-26 11:13:37',
                'updated_at' => '2024-09-26 11:13:37',
                'deleted_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'entertainment_id' => 13,
                'user_id' => 3,
                'profile_id' => 3,
                'entertainment_type' => 'tvshow',
                'watched_time' => '00:04:00',
                'total_watched_time' => '00:04:00',
                'episode_id' => 41,
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => NULL,
                'created_at' => '2024-09-26 11:14:40',
                'updated_at' => '2024-09-26 11:14:40',
                'deleted_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'entertainment_id' => 4,
                'user_id' => 3,
                'profile_id' => 3,
                'entertainment_type' => 'tvshow',
                'watched_time' => '00:05:00',
                'total_watched_time' => '00:05:00',
                'episode_id' => 15,
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => NULL,
                'created_at' => '2024-09-26 11:15:31',
                'updated_at' => '2024-09-26 11:15:31',
                'deleted_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'entertainment_id' => 1,
                'user_id' => 3,
                'profile_id' => 3,
                'entertainment_type' => 'tvshow',
                'watched_time' => '00:01:00',
                'total_watched_time' => '00:01:00',
                'episode_id' => 1,
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => NULL,
                'created_at' => '2024-09-26 11:16:55',
                'updated_at' => '2024-09-26 11:20:23',
                'deleted_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'entertainment_id' => 18,
                'user_id' => 3,
                'profile_id' => 3,
                'entertainment_type' => 'tvshow',
                'watched_time' => '00:05:00',
                'total_watched_time' => '00:05:00',
                'episode_id' => 61,
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => NULL,
                'created_at' => '2024-09-26 11:17:54',
                'updated_at' => '2024-09-26 11:17:54',
                'deleted_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'entertainment_id' => 26,
                'user_id' => 3,
                'profile_id' => 3,
                'entertainment_type' => 'movie',
                'watched_time' => '00:02:00',
                'total_watched_time' => '00:02:00',
                'episode_id' => NULL,
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => NULL,
                'created_at' => '2024-09-26 11:18:35',
                'updated_at' => '2024-09-26 11:18:35',
                'deleted_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'entertainment_id' => 30,
                'user_id' => 3,
                'profile_id' => 3,
                'entertainment_type' => 'movie',
                'watched_time' => '00:03:00',
                'total_watched_time' => '00:03:00',
                'episode_id' => NULL,
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => NULL,
                'created_at' => '2024-09-26 11:19:18',
                'updated_at' => '2024-09-26 11:19:18',
                'deleted_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'entertainment_id' => 2,
                'user_id' => 3,
                'profile_id' => 3,
                'entertainment_type' => 'tvshow',
                'watched_time' => '00:04:00',
                'total_watched_time' => '00:04:00',
                'episode_id' => 9,
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => NULL,
                'created_at' => '2024-09-26 11:19:38',
                'updated_at' => '2024-09-26 11:19:38',
                'deleted_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'entertainment_id' => 80,
                'user_id' => 14,
                'profile_id' => 14,
                'entertainment_type' => 'movie',
                'watched_time' => '00:03:00',
                'total_watched_time' => '00:03:00',
                'episode_id' => NULL,
                'created_by' => 14,
                'updated_by' => 14,
                'deleted_by' => NULL,
                'created_at' => '2024-09-26 11:22:09',
                'updated_at' => '2024-09-26 11:22:09',
                'deleted_at' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'entertainment_id' => 83,
                'user_id' => 14,
                'profile_id' => 14,
                'entertainment_type' => 'movie',
                'watched_time' => '00:04:00',
                'total_watched_time' => '00:04:00',
                'episode_id' => NULL,
                'created_by' => 14,
                'updated_by' => 14,
                'deleted_by' => NULL,
                'created_at' => '2024-09-26 11:23:03',
                'updated_at' => '2024-09-26 11:23:03',
                'deleted_at' => NULL,
            ),
            12 =>
            array (
                'id' => 13,
                'entertainment_id' => 63,
                'user_id' => 14,
                'profile_id' => 14,
                'entertainment_type' => 'movie',
                'watched_time' => '00:02:00',
                'total_watched_time' => '00:02:00',
                'episode_id' => NULL,
                'created_by' => 14,
                'updated_by' => 14,
                'deleted_by' => NULL,
                'created_at' => '2024-09-26 11:24:10',
                'updated_at' => '2024-09-26 11:24:10',
                'deleted_at' => NULL,
            ),
            13 =>
            array (
                'id' => 14,
                'entertainment_id' => 1,
                'user_id' => 14,
                'profile_id' => 14,
                'entertainment_type' => 'tvshow',
                'watched_time' => '00:01:00',
                'total_watched_time' => '00:01:00',
                'episode_id' => 8,
                'created_by' => 14,
                'updated_by' => 14,
                'deleted_by' => NULL,
                'created_at' => '2024-09-26 11:25:25',
                'updated_at' => '2024-09-26 11:25:25',
                'deleted_at' => NULL,
            ),
            14 =>
            array (
                'id' => 15,
                'entertainment_id' => 20,
                'user_id' => 14,
                'profile_id' => 14,
                'entertainment_type' => 'tvshow',
                'watched_time' => '00:03:00',
                'total_watched_time' => '00:03:00',
                'episode_id' => 70,
                'created_by' => 14,
                'updated_by' => 14,
                'deleted_by' => NULL,
                'created_at' => '2024-09-26 11:26:16',
                'updated_at' => '2024-09-26 11:26:16',
                'deleted_at' => NULL,
            ),
            15 =>
            array (
                'id' => 16,
                'entertainment_id' => 19,
                'user_id' => 14,
                'profile_id' => 14,
                'entertainment_type' => 'tvshow',
                'watched_time' => '00:02:00',
                'total_watched_time' => '00:02:00',
                'episode_id' => 64,
                'created_by' => 14,
                'updated_by' => 14,
                'deleted_by' => NULL,
                'created_at' => '2024-09-26 11:26:39',
                'updated_at' => '2024-09-26 11:26:39',
                'deleted_at' => NULL,
            ),
        ));


    }
}
