#!/bin/sh

set -e

echo "=== Xcode Cloud: ci_post_clone.sh ==="

# Install Flutter SDK (latest stable)
echo "Installing Flutter (stable)..."
cd $HOME
git clone https://github.com/flutter/flutter.git -b stable --depth 1 flutter_sdk
export PATH="$PATH:$HOME/flutter_sdk/bin"

echo "Precaching Flutter iOS artifacts..."
flutter precache --ios

echo "Flutter version:"
flutter --version

# Disable Swift Package Manager - force all plugins to use CocoaPods
# (google_mobile_ads depends on webview_flutter_wkwebview as a CocoaPods pod,
#  but Flutter 3.24+ enables SPM by default which skips it as a pod)
flutter config --no-enable-swift-package-manager

# Run flutter pub get in the Flutter project directory
cd $CI_PRIMARY_REPOSITORY_PATH/mobile-app
echo "Running flutter pub get..."
flutter pub get

echo "=== Copying all Flutter generated files to root ios/ ==="

# Copy Flutter build config files (Generated.xcconfig, flutter_export_environment.sh, etc.)
cp -r $CI_PRIMARY_REPOSITORY_PATH/mobile-app/ios/Flutter/ $CI_PRIMARY_REPOSITORY_PATH/ios/Flutter/

# Copy GeneratedPluginRegistrant files (generated by flutter pub get)
if [ -f "$CI_PRIMARY_REPOSITORY_PATH/mobile-app/ios/Runner/GeneratedPluginRegistrant.h" ]; then
    cp $CI_PRIMARY_REPOSITORY_PATH/mobile-app/ios/Runner/GeneratedPluginRegistrant.h $CI_PRIMARY_REPOSITORY_PATH/ios/Runner/GeneratedPluginRegistrant.h
    cp $CI_PRIMARY_REPOSITORY_PATH/mobile-app/ios/Runner/GeneratedPluginRegistrant.m $CI_PRIMARY_REPOSITORY_PATH/ios/Runner/GeneratedPluginRegistrant.m
fi

# Copy pubspec files to repo root so media_kit podspec can find them
# (media_kit_utils.rb searches upward from ENV["PWD"] which is ios/)
cp $CI_PRIMARY_REPOSITORY_PATH/mobile-app/pubspec.yaml $CI_PRIMARY_REPOSITORY_PATH/pubspec.yaml
cp $CI_PRIMARY_REPOSITORY_PATH/mobile-app/pubspec.lock $CI_PRIMARY_REPOSITORY_PATH/pubspec.lock

# Copy Flutter plugin registry files to repo root
# flutter_install_all_ios_pods reads .flutter-plugins-dependencies from parent of ios/ = repo root
if [ -f "$CI_PRIMARY_REPOSITORY_PATH/mobile-app/.flutter-plugins" ]; then
    cp $CI_PRIMARY_REPOSITORY_PATH/mobile-app/.flutter-plugins $CI_PRIMARY_REPOSITORY_PATH/.flutter-plugins
fi
if [ -f "$CI_PRIMARY_REPOSITORY_PATH/mobile-app/.flutter-plugins-dependencies" ]; then
    cp $CI_PRIMARY_REPOSITORY_PATH/mobile-app/.flutter-plugins-dependencies $CI_PRIMARY_REPOSITORY_PATH/.flutter-plugins-dependencies
fi

# Copy plugin symlinks to root ios/ so flutter_install_all_ios_pods finds them
# This makes ios/ look like a standard Flutter ios/ directory to CocoaPods
if [ -d "$CI_PRIMARY_REPOSITORY_PATH/mobile-app/ios/.symlinks" ]; then
    cp -r $CI_PRIMARY_REPOSITORY_PATH/mobile-app/ios/.symlinks $CI_PRIMARY_REPOSITORY_PATH/ios/.symlinks
fi

echo "=== Installing CocoaPods dependencies ==="
# Delete stale Podfile.lock - it locks to old Firebase versions incompatible with current firebase_core
rm -f $CI_PRIMARY_REPOSITORY_PATH/ios/Podfile.lock
# Set PWD_FALLBACK for media_kit as additional fallback to find pubspec.lock
export PWD_FALLBACK=$CI_PRIMARY_REPOSITORY_PATH/mobile-app/ios
cd $CI_PRIMARY_REPOSITORY_PATH/ios
pod install --repo-update

echo "=== ci_post_clone.sh completed successfully ==="
